version: '3.3'
services:
  mysql80:
    platform: linux/amd64
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'forge'
#      MYSQL_USER: 'forge'
#      MYSQL_PASSWORD: 'forge'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./docker/create-mysql-user-for-laravel-framework-test.sql:/docker-entrypoint-initdb.d/1.sql"
#  postgis:
#    platform: linux/amd64
#    image: postgis/postgis:14-master
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: 'forge'
#      POSTGRES_USER: 'forge'
#      POSTGRES_PASSWORD: ''
##      POSTGRES_HOST_AUTH_METHOD: 'trust'

